// eslint-disable-next-line import/prefer-default-export
export const data = [
    {
        id: 1,
        img: "./img/anh1.jpg",
        title: "ĐONG HO NAM",
        desc: "ĐỒNG HỒ LOUIS ERARD 13900AA05.BDC102 NAM PIN DÂY DA",
        price: "18,195,300đ",
    },
    {
        id: 2,
        img: "./img/anh2.jpg",
        title: "ĐONG HO NAM",
        desc: "ĐỒNG HỒ CITIZEN AU1080-20A NAM ECO-DRIVE DÂY VẢI",
        price: "5,040,000đ",
    },
    {
        id: 3,
        img: "./img/anh3.jpg",
        title: "ĐONG HO NAM",
        desc: "ĐỒNG HỒ TISSOT T063.907.11.058.00 NAM TỰ ĐỘNG DÂY INOX",
        price: "21,940,000đ",
    },
    {
        id: 4,
        img: "./img/anh4.jpg",
        title: "ĐONG HO NAM",
        desc: "ĐỒNG HỒ SEIKO SGEG99P1 NAM PIN DÂY DA",
        price: "3,684,000đ",
    },
    {
        id: 5,
        img: "./img/anh5.jpg",
        title: "ĐONG HO NAM",
        desc: "ĐỒNG HỒ ORIENT FSTAA002W0 NAM PIN DÂY DA",
        price: "2,737,000đ",
    },
    {
        id: 6,
        img: "./img/anh6.jpg",
        title: "ĐONG HO NAM",
        desc: "ĐỒNG HỒ OLYM PIANUS OP99141-71AGSK TRẮNG NAM TỰ ĐỘNG DÂY..",
        price: "6,912,000 đ",
    },
    {
        id: 7,
        img: "./img/anh7.jpg",
        title: "ĐONG HO NAM",
        desc: "ĐỒNG HỒ CASIO GA-110GB-1ADR NAM PIN DÂY NHỰA",
        price: "2,584,000đ",
    },
    {
        id: 8,
        img: "./img/anh8.jpg",
        title: "ĐONG HO NAM",
        desc: "ĐỒNG HỒ CASIO MTP-1374L-1AVDF NAM PIN DÂY DA",
        price: "1,677,000đ",
    },
    {
        id: 9,
        img: "./img/9.jpg",
        title: "ĐONG HO NAM",
        desc: "ĐỒNG HỒ TISSOT T41.1.183.34 NỮ TỰ ĐỘNG DÂY INOX",
        price: "17,640,000đ",
    },
    {
        id: 10,
        img: "./img/10.jpg",
        title: "ĐONG HO NAM",
        desc: "ĐỒNG HỒ CITIZEN EX1410-88A NỮ ECO-DRIVE DÂY INOX",
        price: "6,120,000đ",
    },
    {
        id: 11,
        img: "./img/11.jpg",
        title: "ĐONG HO NAM",
        desc: "ĐỒNG HỒ OGIVAL OG385-032LW-T NỮ PIN DÂY INOX",
        price: "9,384,000đ",
    },
    {
        id: 12,
        img: "./img/12.jpg",
        title: "ĐONG HO NAM",
        desc: "ĐỒNG HỒ CANDINO C4433/3 NỮ PIN DÂY INOX",
        price: "3,996,000đ",
    },
    {
        id: 13,
        img: "./img/13.jpg",
        title: "ĐONG HO NAM",
        desc: "ĐỒNG HỒ SKAGEN 885SSLB NỮ PIN DÂY DA",
        price: "5,900,000đ",
    },
    {
        id: 14,
        img: "./img/14.jpg",
        title: "ĐONG HO NAM",
        desc: "ĐỒNG HỒ DANIEL WELLINGTON DW00500001 NỮ PIN DÂY INOX",
        price: "4,230,000đ",
    },
    {
        id: 15,
        img: "./img/15.jpg",
        title: "ĐONG HO NAM",
        desc: "ĐỒNG HỒ CASIO GA-100DE-2ADR NỮ PIN DÂY NHỰA",
        price: "4,393,000đ",
    },
    {
        id: 16,
        img: "./img/16.jpg",
        title: "ĐONG HO NAM",
        desc: "ĐỒNG HỒ CASIO LA670WL-1BDF NỮ PIN DÂY DA",
        price: "766,000đ",
    },
];